INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2003] using WatchFiles
INFO:uvicorn.error:Started server process [2005]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:watchfiles.main:1 change detected: {(<Change.added: 1>, '/vagrant/src/Vagrantfile')}
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for connections to close. (CTRL+C to force quit)
Vagrant exited after cleanup due to external interrupt.
ERROR:src.dependencies:(1, ['/usr/bin/vagrant', 'up'])
Traceback (most recent call last):
  File "/vagrant/src/dependencies.py", line 19, in vagrant_run
    yield v
  File "/vagrant/src/routers/vagrant.py", line 20, in create_vm
    v.up()
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 363, in up
    self._call_vagrant_command(args)
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 1035, in _call_vagrant_command
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'up']' returned non-zero exit status 1.
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2005]
INFO:uvicorn.error:Stopping reloader process [2003]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [3320] using WatchFiles
INFO:uvicorn.error:Started server process [3322]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:watchfiles.main:1 change detected: {(<Change.modified: 2>, '/vagrant/src/Vagrantfile')}
DEBUG:watchfiles.main:1 change detected: {(<Change.modified: 2>, '/vagrant/src/Vagrantfile')}
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [3322]
INFO:uvicorn.error:Stopping reloader process [3320]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [7259] using WatchFiles
INFO:uvicorn.error:Started server process [7283]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:watchfiles.main:1 change detected: {(<Change.modified: 2>, '/vagrant/src/Vagrantfile')}
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [7283]
INFO:uvicorn.error:Stopping reloader process [7259]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [9810] using WatchFiles
INFO:uvicorn.error:Started server process [9812]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:src.dependencies:(2, 'No such file or directory')
Traceback (most recent call last):
  File "/vagrant/src/dependencies.py", line 20, in vagrant_run
    yield v
  File "/vagrant/src/routers/vagrant.py", line 20, in create_vm
    v.up()
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 363, in up
    self._call_vagrant_command(args)
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 1035, in _call_vagrant_command
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/vagrant/usertest/dfsad'
DEBUG:watchfiles.main:1 change detected: {(<Change.modified: 2>, '/vagrant/src/Vagrantfile')}
ERROR:src.dependencies:(2, 'No such file or directory')
Traceback (most recent call last):
  File "/vagrant/src/dependencies.py", line 20, in vagrant_run
    yield v
  File "/vagrant/src/routers/vagrant.py", line 20, in create_vm
    v.up()
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 363, in up
    self._call_vagrant_command(args)
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 1035, in _call_vagrant_command
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/vagrant/usertest/dfsad'
DEBUG:watchfiles.main:1 change detected: {(<Change.modified: 2>, '/vagrant/src/Vagrantfile')}
ERROR:src.dependencies:(2, 'No such file or directory')
Traceback (most recent call last):
  File "/vagrant/src/dependencies.py", line 20, in vagrant_run
    yield v
  File "/vagrant/src/routers/vagrant.py", line 20, in create_vm
    v.up()
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 363, in up
    self._call_vagrant_command(args)
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 1035, in _call_vagrant_command
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/vagrant/usertest/dfsad'
DEBUG:watchfiles.main:1 change detected: {(<Change.modified: 2>, '/vagrant/src/Vagrantfile')}
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [9812]
INFO:uvicorn.error:Stopping reloader process [9810]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [9857] using WatchFiles
INFO:uvicorn.error:Started server process [9859]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [9859]
INFO:uvicorn.error:Stopping reloader process [9857]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [11423] using WatchFiles
INFO:uvicorn.error:Started server process [11425]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [11425]
INFO:uvicorn.error:Stopping reloader process [11423]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [11513] using WatchFiles
INFO:uvicorn.error:Started server process [11515]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [11515]
INFO:uvicorn.error:Stopping reloader process [11513]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [11519] using WatchFiles
INFO:uvicorn.error:Started server process [11521]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [11521]
INFO:uvicorn.error:Stopping reloader process [11519]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [11419] using WatchFiles
INFO:uvicorn.error:Started server process [11421]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [11421]
INFO:uvicorn.error:Stopping reloader process [11419]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [1982] using WatchFiles
INFO:uvicorn.error:Started server process [1984]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:src.dependencies:(2, 'No such file or directory')
Traceback (most recent call last):
  File "/vagrant/src/dependencies.py", line 21, in vagrant_run
    yield v
  File "/vagrant/src/routers/vagrant.py", line 20, in create_vm
    v.up()
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 363, in up
    self._call_vagrant_command(args)
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 1035, in _call_vagrant_command
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/vagrant/usertest/dfsad'
DEBUG:watchfiles.main:1 change detected: {(<Change.modified: 2>, '/vagrant/src/Vagrantfile')}
ERROR:src.dependencies:(2, 'No such file or directory')
Traceback (most recent call last):
  File "/vagrant/src/dependencies.py", line 21, in vagrant_run
    )
  File "/vagrant/src/routers/vagrant.py", line 20, in create_vm
    v.up()
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 363, in up
    self._call_vagrant_command(args)
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 1035, in _call_vagrant_command
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/vagrant/usertest/dfsad'
DEBUG:watchfiles.main:1 change detected: {(<Change.added: 1>, '/vagrant/src/Vagrantfile')}
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1984]
INFO:uvicorn.error:Stopping reloader process [1982]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2354] using WatchFiles
INFO:uvicorn.error:Started server process [2358]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for connections to close. (CTRL+C to force quit)
ERROR:src.dependencies:(1, ['/usr/bin/vagrant', 'up'])
Traceback (most recent call last):
  File "/vagrant/src/dependencies.py", line 23, in vagrant_run
    yield v
  File "/vagrant/src/routers/vagrant.py", line 20, in create_vm
    v.up()
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 363, in up
    self._call_vagrant_command(args)
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 1035, in _call_vagrant_command
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'up']' returned non-zero exit status 1.
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2358]
INFO:uvicorn.error:Stopping reloader process [2354]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [1985] using WatchFiles
INFO:uvicorn.error:Started server process [1987]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Finished server process [1987]
INFO:uvicorn.error:Stopping reloader process [1985]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2367] using WatchFiles
INFO:uvicorn.error:Started server process [2369]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2369]
INFO:uvicorn.error:Stopping reloader process [2367]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2645] using WatchFiles
INFO:uvicorn.error:Started server process [2647]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [11483] using WatchFiles
INFO:uvicorn.error:Started server process [11485]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [11485]
INFO:uvicorn.error:Stopping reloader process [11483]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE host (
	host_id INTEGER NOT NULL, 
	cpu_total INTEGER NOT NULL, 
	mem_total INTEGER NOT NULL, 
	space_total INTEGER NOT NULL, 
	PRIMARY KEY (host_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00015s] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE venv (
	env_id INTEGER NOT NULL, 
	env_name VARCHAR NOT NULL, 
	host_id INTEGER NOT NULL, 
	PRIMARY KEY (env_id), 
	FOREIGN KEY(host_id) REFERENCES host (host_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00019s] ()
INFO:sqlalchemy.engine.Engine:CREATE INDEX ix_venv_env_name ON venv (env_name)
INFO:sqlalchemy.engine.Engine:[no key 0.00016s] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE vm (
	vm_id INTEGER NOT NULL, 
	vm_name VARCHAR NOT NULL, 
	cpu INTEGER NOT NULL, 
	mem INTEGER NOT NULL, 
	space INTEGER NOT NULL, 
	env_id INTEGER NOT NULL, 
	PRIMARY KEY (vm_id), 
	FOREIGN KEY(env_id) REFERENCES venv (env_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00020s] ()
INFO:sqlalchemy.engine.Engine:CREATE INDEX ix_vm_vm_name ON vm (vm_name)
INFO:sqlalchemy.engine.Engine:[no key 0.00021s] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2714] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2716]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2716]
INFO:uvicorn.error:Stopping reloader process [2714]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2721] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2723]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2723]
INFO:uvicorn.error:Stopping reloader process [2721]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE host (
	host_id INTEGER NOT NULL, 
	cpu_total INTEGER NOT NULL, 
	mem_total INTEGER NOT NULL, 
	space_total INTEGER NOT NULL, 
	PRIMARY KEY (host_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00017s] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE venv (
	env_id INTEGER NOT NULL, 
	env_name VARCHAR NOT NULL, 
	host_id INTEGER NOT NULL, 
	PRIMARY KEY (env_id), 
	FOREIGN KEY(host_id) REFERENCES host (host_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00017s] ()
INFO:sqlalchemy.engine.Engine:CREATE INDEX ix_venv_env_name ON venv (env_name)
INFO:sqlalchemy.engine.Engine:[no key 0.00017s] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE vm (
	vm_id INTEGER NOT NULL, 
	vm_name VARCHAR NOT NULL, 
	cpu INTEGER NOT NULL, 
	mem INTEGER NOT NULL, 
	space INTEGER NOT NULL, 
	env_id INTEGER NOT NULL, 
	PRIMARY KEY (vm_id), 
	FOREIGN KEY(env_id) REFERENCES venv (env_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00016s] ()
INFO:sqlalchemy.engine.Engine:CREATE INDEX ix_vm_vm_name ON vm (vm_name)
INFO:sqlalchemy.engine.Engine:[no key 0.00013s] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2727] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2729]
INFO:uvicorn.error:Waiting for application startup.
ERROR:uvicorn.error:Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 692, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/vagrant/src/main.py", line 9, in lifespan
    database.create_db()
AttributeError: module 'src.routers.database' has no attribute 'create_db'

ERROR:uvicorn.error:Application startup failed. Exiting.
INFO:uvicorn.error:Stopping reloader process [2727]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE host (
	host_id INTEGER NOT NULL, 
	cpu_total INTEGER NOT NULL, 
	mem_total INTEGER NOT NULL, 
	space_total INTEGER NOT NULL, 
	PRIMARY KEY (host_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00016s] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE venv (
	env_id INTEGER NOT NULL, 
	env_name VARCHAR NOT NULL, 
	host_id INTEGER NOT NULL, 
	PRIMARY KEY (env_id), 
	FOREIGN KEY(host_id) REFERENCES host (host_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00016s] ()
INFO:sqlalchemy.engine.Engine:CREATE INDEX ix_venv_env_name ON venv (env_name)
INFO:sqlalchemy.engine.Engine:[no key 0.00020s] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE vm (
	vm_id INTEGER NOT NULL, 
	vm_name VARCHAR NOT NULL, 
	cpu INTEGER NOT NULL, 
	mem INTEGER NOT NULL, 
	space INTEGER NOT NULL, 
	env_id INTEGER NOT NULL, 
	PRIMARY KEY (vm_id), 
	FOREIGN KEY(env_id) REFERENCES venv (env_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00016s] ()
INFO:sqlalchemy.engine.Engine:CREATE INDEX ix_vm_vm_name ON vm (vm_name)
INFO:sqlalchemy.engine.Engine:[no key 0.00018s] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2734] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2736]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2736]
INFO:uvicorn.error:Stopping reloader process [2734]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2739] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2741]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2741]
INFO:uvicorn.error:Stopping reloader process [2739]
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2744] using WatchFiles
INFO:uvicorn.error:Started server process [2746]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2746]
INFO:uvicorn.error:Stopping reloader process [2744]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2749] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2751]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2751]
INFO:uvicorn.error:Stopping reloader process [2749]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE host (
	host_id INTEGER NOT NULL, 
	cpu_total INTEGER NOT NULL, 
	mem_total INTEGER NOT NULL, 
	space_total INTEGER NOT NULL, 
	PRIMARY KEY (host_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00015s] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE venv (
	env_id INTEGER NOT NULL, 
	env_name VARCHAR NOT NULL, 
	host_id INTEGER NOT NULL, 
	PRIMARY KEY (env_id), 
	FOREIGN KEY(host_id) REFERENCES host (host_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00013s] ()
INFO:sqlalchemy.engine.Engine:CREATE INDEX ix_venv_env_name ON venv (env_name)
INFO:sqlalchemy.engine.Engine:[no key 0.00012s] ()
INFO:sqlalchemy.engine.Engine:
CREATE TABLE vm (
	vm_id INTEGER NOT NULL, 
	vm_name VARCHAR NOT NULL, 
	cpu INTEGER NOT NULL, 
	mem INTEGER NOT NULL, 
	space INTEGER NOT NULL, 
	env_id INTEGER NOT NULL, 
	PRIMARY KEY (vm_id), 
	FOREIGN KEY(env_id) REFERENCES venv (env_id)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00017s] ()
INFO:sqlalchemy.engine.Engine:CREATE INDEX ix_vm_vm_name ON vm (vm_name)
INFO:sqlalchemy.engine.Engine:[no key 0.00018s] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2754] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2756]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2756]
INFO:uvicorn.error:Stopping reloader process [2754]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [1987] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [1989]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:watchfiles.main:2 changes detected: {(<Change.added: 1>, '/vagrant/src/usertestprueba'), (<Change.modified: 2>, '/vagrant/src/Vagrantfile')}
DEBUG:watchfiles.main:1 change detected: {(<Change.added: 1>, '/vagrant/src/.vagrant/machines/default')}
DEBUG:watchfiles.main:1 change detected: {(<Change.added: 1>, '/vagrant/src/.vagrant/machines/default/virtualbox/vagrant_cwd')}
INFO:uvicorn.error:Shutting down
ERROR:src.dependencies:(1, ['/usr/bin/vagrant', 'up'])
Traceback (most recent call last):
  File "/vagrant/src/dependencies.py", line 33, in vagrant_run
    yield v
  File "/vagrant/src/routers/vagrant.py", line 37, in create_env
    v.up()
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 363, in up
    self._call_vagrant_command(args)
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 1035, in _call_vagrant_command
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'up']' returned non-zero exit status 1.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/vagrant/src/routers/vagrant.py", line 37, in create_env
    v.up()
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 363, in up
    self._call_vagrant_command(args)
  File "/usr/local/lib/python3.10/dist-packages/vagrant/__init__.py", line 1035, in _call_vagrant_command
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'up']' returned non-zero exit status 1.
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [1989]
INFO:uvicorn.error:Stopping reloader process [1987]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2180] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2182]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2182]
INFO:uvicorn.error:Stopping reloader process [2180]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2194] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2196]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2196]
INFO:uvicorn.error:Stopping reloader process [2194]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2202] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2206]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/vagrant/src/routers/vagrant.py", line 34, in create_env
    os.mkdir(env_path)
FileNotFoundError: [Errno 2] No such file or directory: 'usertest/prueba/dd'
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2206]
INFO:uvicorn.error:Stopping reloader process [2202]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2221] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2223]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/vagrant/src/routers/vagrant.py", line 34, in create_env
    os.mkdir(env_path)
FileNotFoundError: [Errno 2] No such file or directory: 'usertest/prueba/dd'
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/vagrant/src/routers/vagrant.py", line 34, in create_env
    )
FileNotFoundError: [Errno 2] No such file or directory: 'usertest/prueba/dd'
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2223]
INFO:uvicorn.error:Stopping reloader process [2221]
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Will watch for changes in these directories: ['/vagrant/src']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [2250] using WatchFiles
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("vm")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("venv")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("host")
INFO:sqlalchemy.engine.Engine:[raw sql] ()
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:uvicorn.error:Started server process [2252]
INFO:uvicorn.error:Waiting for application startup.
INFO:uvicorn.error:Application startup complete.
DEBUG:watchfiles.main:1 change detected: {(<Change.modified: 2>, '/vagrant/src/Vagrantfile')}
INFO:uvicorn.error:Shutting down
INFO:uvicorn.error:Waiting for application shutdown.
INFO:uvicorn.error:Application shutdown complete.
INFO:uvicorn.error:Finished server process [2252]
INFO:uvicorn.error:Stopping reloader process [2250]
